import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";

export function TermsAndConditions() {
  return (
    <div className="min-h-screen bg-background py-8">
      <div className="container mx-auto px-4 max-w-4xl">
        <Card>
          <CardHeader>
            <CardTitle className="text-3xl font-bold">Terms and Conditions</CardTitle>
            <CardDescription>
              Last updated: {new Date().toLocaleDateString()}
            </CardDescription>
          </CardHeader>
          <CardContent>
            <ScrollArea className="h-[70vh] pr-4">
              <div className="space-y-8 text-sm leading-relaxed">
                
                {/* Introduction */}
                <section>
                  <h2 className="text-xl font-semibold mb-4">1. Introduction</h2>
                  <p className="mb-4">
                    Welcome to Dine-N ("we," "our," or "us"). These Terms and Conditions ("Terms") govern your use of our meal planning application and related services (the "Service"). By accessing or using our Service, you agree to be bound by these Terms.
                  </p>
                  <p>
                    If you disagree with any part of these terms, then you may not access the Service.
                  </p>
                </section>

                {/* AI-Generated Content Disclaimer */}
                <section>
                  <h2 className="text-xl font-semibold mb-4">2. AI-Generated Content Disclaimer</h2>
                  <div className="bg-yellow-50 dark:bg-yellow-950 border border-yellow-200 dark:border-yellow-800 rounded-lg p-4 mb-4">
                    <h3 className="font-semibold text-yellow-800 dark:text-yellow-200 mb-2">⚠️ Important Notice</h3>
                    <p className="text-yellow-700 dark:text-yellow-300">
                      All meal plans, recipes, and nutritional information provided by Dine-N are generated by artificial intelligence and are for informational purposes only.
                    </p>
                  </div>
                  <div className="space-y-4">
                    <p>
                      <strong>Medical Disclaimer:</strong> This content does not constitute medical, nutritional, or dietary advice. You should consult with qualified healthcare professionals before making any dietary changes, especially if you have medical conditions, allergies, or special dietary requirements.
                    </p>
                    <p>
                      <strong>User Responsibility:</strong> You are solely responsible for:
                    </p>
                    <ul className="list-disc pl-6 space-y-2">
                      <li>Verifying the safety and suitability of all recipes and ingredients</li>
                      <li>Checking for food allergies and dietary restrictions</li>
                      <li>Following proper food handling and cooking procedures</li>
                      <li>Ensuring ingredient freshness and quality</li>
                      <li>Using your own judgment and culinary knowledge</li>
                    </ul>
                    <p>
                      <strong>Limitation of Liability:</strong> Dine-N disclaims all liability for any adverse reactions, health issues, food poisoning, allergic reactions, or damages resulting from the use of AI-generated content. Our AI system, while sophisticated, may occasionally generate inaccurate or inappropriate content.
                    </p>
                  </div>
                </section>

                {/* Food Safety & Allergies */}
                <section>
                  <h2 className="text-xl font-semibold mb-4">3. Food Safety & Allergy Warning</h2>
                  <div className="bg-red-50 dark:bg-red-950 border border-red-200 dark:border-red-800 rounded-lg p-4 mb-4">
                    <h3 className="font-semibold text-red-800 dark:text-red-200 mb-2">🚨 Critical Safety Information</h3>
                    <p className="text-red-700 dark:text-red-300">
                      Users with severe allergies or medical conditions must independently verify all ingredients and consult with healthcare professionals before consuming any recommended foods.
                    </p>
                  </div>
                  <p className="mb-4">
                    While our system attempts to accommodate specified allergies and dietary restrictions, we cannot guarantee the accuracy of allergen information. Cross-contamination and ingredient variations may occur.
                  </p>
                  <p>
                    You acknowledge that food safety is paramount and agree to follow proper food handling, storage, and cooking procedures as recommended by food safety authorities.
                  </p>
                </section>

                {/* Account Terms */}
                <section>
                  <h2 className="text-xl font-semibold mb-4">4. Account Terms</h2>
                  <div className="space-y-4">
                    <p>
                      <strong>Registration:</strong> You must provide accurate, current, and complete information during registration and keep your account information updated.
                    </p>
                    <p>
                      <strong>Account Security:</strong> You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.
                    </p>
                    <p>
                      <strong>Age Requirement:</strong> You must be at least 13 years old to use this Service. Users under 18 must have parental consent.
                    </p>
                  </div>
                </section>

                {/* Subscription Terms */}
                <section>
                  <h2 className="text-xl font-semibold mb-4">5. Subscription Terms & Billing</h2>
                  <div className="space-y-4">
                    <p>
                      <strong>Free Tier:</strong> Free accounts are limited to 1 meal plan generation. Additional features may be restricted.
                    </p>
                    <p>
                      <strong>Premium Subscription:</strong> Premium subscriptions are billed monthly at $9.99/month and provide unlimited meal plan generation and access to premium features.
                    </p>
                    <p>
                      <strong>Billing:</strong> Subscriptions automatically renew unless cancelled. You will be charged at the beginning of each billing cycle.
                    </p>
                    <p>
                      <strong>Cancellation:</strong> You may cancel your subscription at any time. Cancellation takes effect at the end of your current billing period, and you will retain access to premium features until then.
                    </p>
                    <p>
                      <strong>Refunds:</strong> We do not provide refunds for partial months of service. All sales are final.
                    </p>
                    <p>
                      <strong>Price Changes:</strong> We reserve the right to modify subscription prices with 30 days' notice to existing subscribers.
                    </p>
                  </div>
                </section>

                {/* Data Collection & Privacy */}
                <section>
                  <h2 className="text-xl font-semibold mb-4">6. Data Collection & Privacy</h2>
                  <div className="space-y-4">
                    <p>
                      <strong>Analytics Data:</strong> We collect minimal, non-personal analytics data to improve our service, including:
                    </p>
                    <ul className="list-disc pl-6 space-y-1">
                      <li>Page views and user interactions</li>
                      <li>Feature usage patterns</li>
                      <li>Performance metrics</li>
                      <li>Error logs</li>
                    </ul>
                    <p>
                      <strong>Personal Data:</strong> We do not collect, store, or sell personal information beyond what is necessary for account creation and service provision. All analytics data is anonymized and used solely for service improvement purposes.
                    </p>
                    <p>
                      <strong>Dietary Preferences:</strong> Your dietary preferences and meal plans are stored securely and used only to provide personalized recommendations.
                    </p>
                  </div>
                </section>

                {/* Intellectual Property */}
                <section>
                  <h2 className="text-xl font-semibold mb-4">7. Intellectual Property</h2>
                  <div className="space-y-4">
                    <p>
                      <strong>Service Content:</strong> The Service and its original content, features, and functionality are owned by Dine-N and are protected by international copyright, trademark, and other intellectual property laws.
                    </p>
                    <p>
                      <strong>AI-Generated Content:</strong> Recipes and meal plans generated by our AI system are provided for your personal use. You may save, print, and share them for non-commercial purposes.
                    </p>
                    <p>
                      <strong>User Content:</strong> You retain ownership of any content you submit to the Service, but grant us a license to use it for service provision and improvement.
                    </p>
                  </div>
                </section>

                {/* Service Availability */}
                <section>
                  <h2 className="text-xl font-semibold mb-4">8. Service Availability</h2>
                  <div className="space-y-4">
                    <p>
                      <strong>Uptime:</strong> We strive to maintain high service availability but do not guarantee uninterrupted access to the Service.
                    </p>
                    <p>
                      <strong>Maintenance:</strong> We reserve the right to modify, suspend, or discontinue the Service or any features with or without notice for maintenance, updates, or other operational reasons.
                    </p>
                    <p>
                      <strong>Technical Issues:</strong> We are not liable for any loss or damage resulting from service interruptions, technical difficulties, or system failures.
                    </p>
                  </div>
                </section>

                {/* User Conduct */}
                <section>
                  <h2 className="text-xl font-semibold mb-4">9. User Conduct</h2>
                  <p className="mb-4">You agree not to:</p>
                  <ul className="list-disc pl-6 space-y-2">
                    <li>Use the Service for any unlawful purpose or in violation of any applicable laws</li>
                    <li>Attempt to gain unauthorized access to the Service or other users' accounts</li>
                    <li>Interfere with or disrupt the Service or servers</li>
                    <li>Use automated systems to access the Service without permission</li>
                    <li>Share your account credentials with others</li>
                    <li>Use the Service to distribute harmful, offensive, or inappropriate content</li>
                  </ul>
                </section>

                {/* Limitation of Liability */}
                <section>
                  <h2 className="text-xl font-semibold mb-4">10. Limitation of Liability</h2>
                  <div className="bg-muted border border-border rounded-lg p-4 mb-4">
                    <p className="font-semibold mb-2">IMPORTANT LEGAL NOTICE</p>
                    <p className="text-sm">
                      TO THE MAXIMUM EXTENT PERMITTED BY LAW, DINE-N SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, USE, OR OTHER INTANGIBLE LOSSES.
                    </p>
                  </div>
                  <p className="mb-4">
                    Our total liability to you for all claims arising from or relating to the Service shall not exceed the amount you paid us in the 12 months preceding the claim, or $100, whichever is greater.
                  </p>
                  <p>
                    Some jurisdictions do not allow the exclusion or limitation of certain damages, so some of the above limitations may not apply to you.
                  </p>
                </section>

                {/* Indemnification */}
                <section>
                  <h2 className="text-xl font-semibold mb-4">11. Indemnification</h2>
                  <p>
                    You agree to indemnify, defend, and hold harmless Dine-N and its officers, directors, employees, and agents from any claims, damages, losses, or expenses (including reasonable attorneys' fees) arising from your use of the Service, violation of these Terms, or infringement of any rights of another party.
                  </p>
                </section>

                {/* Termination */}
                <section>
                  <h2 className="text-xl font-semibold mb-4">12. Termination</h2>
                  <div className="space-y-4">
                    <p>
                      <strong>By You:</strong> You may terminate your account at any time by contacting us or using the account deletion feature.
                    </p>
                    <p>
                      <strong>By Us:</strong> We may terminate or suspend your account immediately, without prior notice, for conduct that we believe violates these Terms or is harmful to other users or the Service.
                    </p>
                    <p>
                      <strong>Effect of Termination:</strong> Upon termination, your right to use the Service will cease immediately, and we may delete your account and data.
                    </p>
                  </div>
                </section>

                {/* Dispute Resolution */}
                <section>
                  <h2 className="text-xl font-semibold mb-4">13. Dispute Resolution</h2>
                  <div className="space-y-4">
                    <p>
                      <strong>Governing Law:</strong> These Terms are governed by and construed in accordance with the laws of [Your Jurisdiction], without regard to conflict of law principles.
                    </p>
                    <p>
                      <strong>Informal Resolution:</strong> Before filing any formal dispute, you agree to first contact us to attempt to resolve the issue informally.
                    </p>
                    <p>
                      <strong>Jurisdiction:</strong> Any legal action or proceeding arising under these Terms will be brought exclusively in the courts of [Your Jurisdiction].
                    </p>
                  </div>
                </section>

                {/* Changes to Terms */}
                <section>
                  <h2 className="text-xl font-semibold mb-4">14. Changes to Terms</h2>
                  <p className="mb-4">
                    We reserve the right to modify these Terms at any time. We will notify users of material changes by email or through the Service at least 30 days before the changes take effect.
                  </p>
                  <p>
                    Your continued use of the Service after changes become effective constitutes acceptance of the new Terms.
                  </p>
                </section>

                {/* Severability */}
                <section>
                  <h2 className="text-xl font-semibold mb-4">15. Severability</h2>
                  <p>
                    If any provision of these Terms is held to be invalid or unenforceable, the remaining provisions will remain in full force and effect, and the invalid provision will be replaced with a valid provision that most closely reflects the intent of the original.
                  </p>
                </section>

                {/* Contact Information */}
                <section>
                  <h2 className="text-xl font-semibold mb-4">16. Contact Information</h2>
                  <p className="mb-4">
                    If you have any questions about these Terms and Conditions, please contact us at:
                  </p>
                  <div className="bg-blue-50 dark:bg-blue-950 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
                    <p className="text-blue-900 dark:text-blue-100"><strong>Email:</strong> legal@dine-n.com</p>
                    <p className="text-blue-900 dark:text-blue-100"><strong>Address:</strong> [Your Business Address]</p>
                    <p className="text-blue-900 dark:text-blue-100"><strong>Phone:</strong> [Your Phone Number]</p>
                  </div>
                </section>

                {/* Acknowledgment */}
                <section className="border-t pt-6">
                  <h2 className="text-xl font-semibold mb-4">Acknowledgment</h2>
                  <p className="font-medium">
                    By using Dine-N, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions. You also acknowledge that you understand the AI-generated nature of our content and will exercise appropriate judgment when using our recommendations.
                  </p>
                </section>

              </div>
            </ScrollArea>
          </CardContent>
        </Card>
      </div>
    </div>
  );
} 